CC = g++
CFLAGS = -std=c++11

SRCS = linked_list.cpp linked_list_driver.cpp

linked_list.o: $(SRCS)
	$(CC) $(CFLAGS) $(SRCS) -o linked_list.o

clean:
	Del "C:\Users\Ethan Rivers\Documents\AdvCompProg-Work\linked_list\linked_list\linked_list.o"