CC = g++
SRC_DIR = ..
INC_DIR = ..
CFLAGS = -std=c++11 -I$(INC_DIR)

SRCS = $(SRC_DIR)\hash_table.h $(SRC_DIR)\hash\hash_table.cpp $(SRC_DIR)\hash\hash_table_driver.cpp

hash_table.o: $(SRCS)
	$(CC) $(CFLAGS) $(SRCS) -o hash_table.o

clean:
	Del "C:\Users\Ethan Rivers\Documents\AdvCompProg-Work\template_library\Util\hash\hash_table.o"
