CC = g++
CFLAGS = -std=c++11 -I..\hash -I..\circular_list

SRCS = directed_graph.h directed_graph.cpp directed_graph_driver.cpp

directed_graph.o: $(SRCS)
	$(CC) $(CFLAGS) $(SRCS) -o directed_graph.o

clean:
	Del "C:\Users\Ethan Rivers\Documents\AdvCompProg-Work\directed_graph\directed_graph.o"