CC = g++
SRC_DIR = directed_graph
INC_DIR = Util
CFLAGS = -std=c++11 -I$(INC_DIR)

SRCS = $(SRC_DIR)\directed_graph.cpp $(SRC_DIR)\directed_graph_driver.cpp $(SRC_DIR)\directed_graph.h

directed_graph.o: $(SRCS)
	$(CC) $(CFLAGS) $(SRCS) -o directed_graph.o

clean:
	Del "C:\Users\Ethan Rivers\Documents\AdvCompProg-Work\template_library\directed_graph.o"